version: '3.9'
services:
  # client:
  #   build: 
  #     context: ./client
  #   container_name: easyeats_frontend
  #   ports:
  #     - "5000:8080"
  #   networks:
  #     - my-network
  # server:
  #   build:
  #     context: ./server
  #   container_name: easyeats_backend
  #   ports:
  #     - "4000:4000"
  #   links: 
  #     - bd
  #   restart: always
  #   networks:
  #     - my-network
  bd:
    image: mariadb/server:10.3
    restart: always
    container_name: easyeats_db
    hostname: easy_eats_database
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: easy_eats_db
    volumes:
      - ./easy_eats_db.sql:/docker-entrypoint-initdb.d/easy_eats_db.sql
    networks:
      - my-network
  phpmyadmin:
    image: phpmyadmin
    container_name: easyeats_phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - my-network
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=easyeats_db
      - PMA_PORT=3306
      - PMA_USER=easy_eats_us
      - PMA_PASSWORD=admin
networks:
  my-network:
    driver: bridge
    

